### ISSUE TITLE
Notebook outdated

### ISSUE THREAD

**Issue by evanmiltenburg** [ramakrishnavedantam928/pyCider#2]
The notebook is outdated. It calls `ciderEval` with two arguments, whereas the `CIDErEvalCap` class is defined with 3 arguments: `(self, gts, res, df)`. Hence it doesn't work, because the `df`-argument is not specified.

**Comment by evanmiltenburg** [comment]
The notebook does work for me at this point in time: https://github.com/vrama91/cider/tree/5f721627b9aa6e760f100354ef926577d337d288

This repository doesn't contain the data yet, but using the data from the most recent version, I got it to work. The problem for me is that I want to evaluate single candidates on 5 references. The README from the most recent commit suggests that I should "Set the "idf" value to "coco-val-df" if evaluating on a single image." But that does not work, due to #3.

**Comment by ramavedantam** [comment]
Thanks for pointing this out! I updated the notebook, should work fine now.

**Comment by evanmiltenburg** [comment]
Thank you!
