### ISSUE TITLE
CIDEr score above 1

### ISSUE THREAD

**Issue by Crista23** [ramakrishnavedantam928/pyCider#4]
When testing CIDEr with one reference sentence for each candidate sentence, I get a CIDEr score of 7.24. Since CIDEr computes the average cosine similarity between a candidate and a reference, is it normal for CIDEr values to be above 1? Thank you!

**Comment by ramavedantam** [comment]
Yes, it is normal for CIDEr-D values to be greater than 1, infact the maximum value is 10, because the cosine similarity is multiplied by 10 (See Eqn. 4 in https://arxiv.org/pdf/1411.5726.pdf).

**Comment by liujqian** [comment]
Why are both the CIDEr score and the CIDEr-D score implementations multiplied by 10 in the end? I can get both metrics above one. Is there any implementation error for the original CIDEr score?
